[theme]
base="dark"
primaryColor="#5E60D2"
backgroundColor="#1e272e"
secondaryBackgroundColor="#2a333c"

textColor="#e6e6ea"
font="Quicksand:https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap"

# baseRadius="full"
# dataframeHeaderBackgroundColor="#141f25"


[theme.sidebar]
backgroundColor="#141f25"
secondaryBackgroundColor="#1d2b36"
